openapi: 3.0.0
info:
  title: API pour la création d'offres de stage sur monstagedetroisieme.fr
  description: API pour la création d'offres de stages à destination des élèves de
    collège en REP ou REP+
  contact:
    email: etienne.weil@monstagedetroisieme.fr
  version: 1.0.0
servers:
- url: http://localhost:3000/api
  description: SwaggerHub API Auto Mocking
security:
- bearerAuth: []
tags:
- name: developers
  description: Operations accessibles aux développeurs disposant d'une clé API
paths:
  /internship_offers:
    get:
      tags:
        - developers
      summary: liste (index) les offres déposées
      operationId: internship_offers_index
      security:
        - bearerAuth: []
      description: |
        Les offres retournées sont celles qui ont été déposées par les partenaires de monstagedetroisieme.fr
      responses:
        '200':
          description: Offre de stage créée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternshipOffers'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          description: Un argument de la requête fait échouer la requête.
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    example: "NOT_FOUND"
                  error:
                    type: string
                    example: "can't find internship_offer with this remote_id"
                  status:
                    type: string
                    example: "not_found"
    post:
      tags:
      - developers
      summary: ajoute une offre de stage d'un partenaire aux offres proposées en propre
        par les équipes monstagedetroisieme.fr
      description: |
        Les offres de stages décrits ci-dessous décrivent les offres réservées aux classes de **troisiemeen REP  ou REP+**, anciennement nommées troisieme générale
      operationId: internship_offers
      requestBody:
        $ref: '#/components/requestBodies/InternshipOffer'
      responses:
        "201":
          description: Offre de stage créée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternshipOffer'
        "401":
          description: l'authentification a échoué
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_401'
        "403":
          description: L'utilisateur n'est pas autorisé à supprimer cette offre de
            stage
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_403'
        "404":
          description: Un argument de la requête fait échouer la requête.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_404'
        "406":
          description: Un ou plusieurs paramètres de requête sont invalides
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_406'
        "409":
          description: Conflit. Une offre de stage avec le même remote_id existe déjà
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_409'
        "422":
          description: Un argument au moins de la requête fait échouer la requête
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_422'
      security:
      - bearerAuth: []
      x-swagger-router-controller: Developers
  /internship_offers/{remote_id}:
    delete:
      tags:
      - developers
      summary: Supprime une offre de stage d'un partenaire des offres proposées sur
        le site monstagedetroisieme.fr
      description: |
        Suppression des offres
      operationId: internship_offers_delete
      parameters:
      - name: remote_id
        in: path
        description: id de l'offre de stage
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: remote-123
      responses:
        "200":
          description: Offre de stage supprimée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternshipOffer'
        "401":
          description: l'authentification a échoué
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_401'
        "403":
          description: L'utilisateur n'est pas autorisé à supprimer cette offre de
            stage
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_403'
        "404":
          description: Un argument de la requête fait échouer la requête.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_404'
        "422":
          description: Un argument de la requête fait échouer la requête.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_422'
      security:
      - bearerAuth: []
      x-swagger-router-controller: Developers
    patch:
      tags:
      - developers
      summary: met à jour une offre de stage d'un partenaire aux offres proposées
        en propre par les équipes monstagedetroisieme.fr
      description: |
        Mise à jour des offres . Possibilité de désactiver son offre en passant le paramètre published_at à null
      operationId: internship_offers_updatte
      parameters:
      - name: remote_id
        in: path
        description: "clé étrangère unique , id de l'offre de stage chez le partenaire"
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: remote-123
      requestBody:
        $ref: '#/components/requestBodies/InternshipOfferPatch'
      responses:
        "200":
          description: Offre de stage mise à jour
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternshipOffer'
        "401":
          description: l'authentification a échoué
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_401'
        "403":
          description: L'utilisateur n'est pas autorisé à supprimer cette offre de
            stage
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_403'
        "404":
          description: Un argument de la requête fait échouer la requête.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_404'
        "406":
          description: Un ou plusieurs paramètres de requête sont invalides
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_406'
        "422":
          description: Un argument au moins de la requête fait échouer la requête
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_422'
      security:
      - bearerAuth: []
      x-swagger-router-controller: Developers
  /sectors:
    get:
      tags:
      - developers
      summary: Récupère la liste des secteurs économiques
      description: "Secteur économique. [https://github.com/betagouv/monstage/blob/staging/doc/README.md](https://github.com/betagouv/monstage/blob/staging/doc/README.md)"
      operationId: sectors
      responses:
        "200":
          description: Liste des secteurs économiques
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Sector'
                x-content-type: application/json
      security:
      - bearerAuth: []
      x-swagger-router-controller: Developers
components:
  schemas:
    InternshipOffers:
      type: array
      items:
        $ref: '#/components/schemas/InternshipOffer'
    InternshipOffer:
      required:
      - city
      - coordinates
      - employer_name
      - is_public
      - max_candidates
      - remote_id
      - sector_id
      - street
      - title
      - weeks
      type: object
      properties:
        description:
          maxLength: 500
          type: string
          description: Description de l'offre de stage
        title:
          type: string
          example: Stage d'observation du métier de chef de service
        employer_name:
          type: string
          example: BNP Paribas
        employer_description:
          maxLength: 275
          type: string
          example: "Créateur de lotions, de parfums et de produits cosmétiques, embaumeur"
        street:
          type: string
          example: 16 rue de la paix
        city:
          type: string
          example: Paris
        zipcode:
          type: string
          example: "75001"
        employer_website:
          type: string
          example: http://www.acnee-corporation.fr
        remote_id:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
          description: Identifiant de l'offre de stage chez le partenaire
          example: 123
        lunch_break:
          type: string
          description: Horaires de pause déjeuner
          example: 12h-14h
        daily_hours:
          type: object
          description: Horaires de travail
          example:
            lundi:
            - 9:00
            - 18:00
            mardi:
            - 9:00
            - 18:00
            mercredi:
            - 9:00
            - 18:00
            jeudi:
            - 9:00
            - 18:00
            vendredi:
            - 9:00
            - 18:00
        coordinates:
          type: object
          description: Coordonnées géographiques du lieu de stage
          example:
            latitude: 1
            longitude: 1
        weeks:
          type: array
          description: Semaines de stage proposées
          example:
          - 2020-W16
          - 2020-W17
          items:
            type: string
            description: Semaine de stage
        permalink:
          type: string
          description: Site de l'employeur
          example: http://www.stagechezemployeur.fr
        max_candidates:
          type: integer
          description: Nombre maximum de candidats pouvant postuler à cette offre
            de stage sur l'ensemble des semaines proposées
          example: 1
        is_public:
          type: boolean
          description: "true si l'offre de stage est issue d'une administration publique,\
            \ false si elle est issue d'une entreprise privée"
          example: true
        sector_id:
          $ref: '#/components/schemas/Sector'
      description: offre de stage
      example:
        weeks:
        - 2020-W16
        - 2020-W17
        city: Paris
        remote_id: 123
        coordinates:
          latitude: 1
          longitude: 1
        description: description
        employer_description: "Créateur de lotions, de parfums et de produits cosmé\
          tiques, embaumeur"
        employer_name: BNP Paribas
        title: Stage d'observation du métier de chef de service
        lunch_break: 12h-14h
        zipcode: "75001"
        max_candidates: 1
        employer_website: http://www.acnee-corporation.fr
        sector_id:
          sector_uuid: b7564ac4-e184-41c4-a7a9-57233a9d244a
          name: Mode
          id: 1
        street: 16 rue de la paix
        is_public: true
        permalink: http://www.stagechezemployeur.fr
        daily_hours:
          lundi:
          - 9:00
          - 18:00
          mardi:
          - 9:00
          - 18:00
          mercredi:
          - 9:00
          - 18:00
          jeudi:
          - 9:00
          - 18:00
          vendredi:
          - 9:00
          - 18:00
    InternshipOfferPatch:
      allOf:
      - type: object
        properties:
          published_at:
            type: string
            format: date-time
      - $ref: '#/components/schemas/InternshipOffer'
    Sector:
      type: object
      properties:
        id:
          type: number
          example: 1
        sector_uuid:
          type: string
          format: uuid
          example: b7564ac4-e184-41c4-a7a9-57233a9d244a
        name:
          type: string
          example: Mode
      description: Secteur économique.
      example:
        sector_uuid: b7564ac4-e184-41c4-a7a9-57233a9d244a
        name: Mode
        id: 1
    inline_response_401:
      type: object
      properties:
        code:
          type: string
          example: UNAUTHORIZED
        error:
          type: string
          example: access denied
        status:
          type: string
          example: unauthorized
    inline_response_403:
      type: object
      properties:
        code:
          type: string
          example: FORBIDDEN
        error:
          type: string
          example: access denied
        status:
          type: string
          example: forbidden
    inline_response_404:
      type: object
      properties:
        code:
          type: string
          example: NOT_FOUND
        error:
          type: string
          example: can't find internship_offer with this remote_id
        status:
          type: string
          example: not_found
    inline_response_406:
      type: object
      properties:
        code:
          type: string
          example: VALIDATION_ERROR
        error:
          type: string
          example: Erreur de validation sur l'objet
        status:
          type: string
          example: conflict
    inline_response_409:
      type: object
      properties:
        code:
          type: string
          example: DUPLICATE_WEEKY_FRAMED
        error:
          type: string
          example: weeky_framed with this remote_id (123) already exists.
        status:
          type: string
          example: conflict
    inline_response_422:
      type: object
      properties:
        code:
          type: string
          example: BAD_ARGUMENT
        error:
          type: string
          example: Erreur sur la requête due à un un paramètre invalide
        status:
          type: string
          example: unprocessable_entity
  responses:
    Unauthorized:
      description: l'authentification a échoué
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_response_401'
  requestBodies:
    InternshipOffer:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InternshipOffer'
    InternshipOfferPatch:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InternshipOfferPatch'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT